### ISSUE TITLE
Move installation

### ISSUE THREAD

**Issue by philrosenberg** [fsquillace/junest#101]
Hi
Is it possible to move a juNest installation? My home directory which contains my juNest install is on a network drive. However I have limited space on there and I would now like to move my installation to a local drive where I have much more space.

Phil

**Comment by fsquillace** [comment]
Hi,
The JuNest location is ~/.junest directory (unless you have specified elsewhere via JUNEST_HOME variable). So, you  can move that directory somewhere else and then run:

    JUNEST_HOME=/new/junest/path junest

**Comment by philrosenberg** [comment]
Thanks, that worked.
Initially I tried setting JUNEST_HOME as a variable in my .cshrc, but this didn't work. I guess because the bash shebang  causes a new bash session to open which does not inherit the environment variables

**Comment by fsquillace** [comment]
I think you could also define the variable in .cshrc but maybe you need to use export.

    export JUNEST_HOME=/new/junest/path

Closing issue.

Cheers,
Filippo
