### ISSUE TITLE
yaourt fails to install package

### ISSUE THREAD

**Issue by mardukbp** [fsquillace/junest#106]
I run `junest`. 

Then `yaourt -S rofi`and I get `/usr/lib/yaourt/util.sh: line 102: su: command not found`.

I am using Ubuntu 15.04.

Thank you so much for this amazing software!

**Comment by fsquillace** [comment]
Hi,

If you need to install packages from AUR you need to install the base-devel package group first:

    pacman -S base-devel

This is reported in the troubleshoot section in the README too.

Cheers, 
Filippo

**Comment by mardukbp** [comment]
Thanks!
