### ISSUE TITLE
SSHFS mount in junest

### ISSUE THREAD

**Issue by sea3pea0** [fsquillace/junest#109]
I have a synology nas and I haven't figured out a way to get sshfs installed directly so I thought I'd give junest a try. I am able to install fuse and sshfs in junest but haven't had any luck mounting a folder.

Here are the exact steps I take:
1. I launch junest with: junest -p "-b /volume1/download:/mnt/download"
2. I edited /etc/fuse.conf and uncommented user_allow_other
3. mkdir /mnt/download/sshfs
4. I try to mount the remote folder: sshfs -o idmap=user someuser@somesit.com: /mnt/download/sshfs

This is the message I get: fusermount: mount failed: Operation not permitted

Is this possible in junest? If so can anyone tell me what I can do to make this work?

Thanks!

**Comment by fsquillace** [comment]
Hi,
I think that is because you still need to have the fuser kernel module activated and that it would require to be root. You can try the steps 1 to 3 by using the fakeroot (junest -f).
Then, for the step you still need to be root (sudo junest -r).

I could not make any test right now. I will personally try it in the next weeks.

Regards

**Comment by sea3pea0** [comment]
Hi, thanks for your quick response,

Okay made some progress with this. I am able to mount the folder successfully starting out with "sudo junest -r". Running that from a user account ends up running junest from /root/.junest instead of the user account home folder. So from step 1 I don't have the folder bound to /mnt/download/sshfs. Also if I try to run junest -p "-b /volume1/download:/mnt/download" from the root account to get the host directory bound to the guest location, I get: You cannot access with root privileges. Use --root option instead.
I would like to be able to get the sshfs mount outside of the /root folder on my syno.

Regards

**Comment by sea3pea0** [comment]
Update: I pretty much got it working. Although maybe there's a better way (more secure) to do what I'm trying to accomplish. 

Here's what I've done:

1. From root account - junest -r
2. From within junest - Installed sshfs
3. Edit /etc/fuse.conf - user_allow_other
4. From outside junest I had to chmod 755 /root, chmod 755 /root/.junest and chmod 755 /root/.junest/mnt to allow the user access to the location where the sshfs mount will be
5. From within junest - mkdir /mnt/sshfs 
6. From outside Junest chown (user that I want to access mount with):(group I want to access mount with) /root/.junest/mnt/sshfs
7. From outside junest - ln -s /root/.junest/mnt/sshfs /volume1/download
7. From inside junest sshfs -o idmap=user -o uid=(uid of user that I want to access mount with) -o gid=(gid of user that I want to give access to mount) -o allow_other someuser@somesite.com: /mnt/sshfs

**Comment by sea3pea0** [comment]
I ended up making an spk for synocommunity that accomplishes what I needed, an sshfs mount on a synology nas. So, I don't really need to do this with Junest anymore. Thanks for your help.
