### ISSUE TITLE
Run a program inside JuNest from a shell script in host system

### ISSUE THREAD

**Issue by mardukbp** [fsquillace/junest#112]
I have a Debian workstation at the university and I installed JuNest in my $HOME folder in order to be able to install my own programs. I would like to make it easier to run programs inside JuNest from the Debian host. For that purpose, I want to write a shell script that executes the `junest` command and then runs a specified program. However, I am having difficulties with the fact that `junest` creates a subshell (what is the proper term?). I do not know how to pass commands to the junest shell.

**Comment by fsquillace** [comment]
Hi,

You can even pass the command through the CLI. For instance:

    junest -f -- pacman -Syu
    ....

Will update the JuNest system.

**Comment by mardukbp** [comment]
Fantastic! Thank you!
