### ISSUE TITLE
Do not run non-interactive user command two times, when it fails

### ISSUE THREAD

**Issue by RomanSaveljev** [fsquillace/junest#113]
As I understood from @fsquillace this was a workaround to figure out whether proot returns error, because it did not not like some parameters, or it is from its child process.

Another solution is proposed:

> Try first a dummy command, which always succeeds, to validate proot setting and then run the real command and only once

The following is a suitable dummy command, which does not impose anymore binary dependencies on the contents of the junest image:

```
proot-x86_64 -R /home/user/.junest /bin/sh --login -c ":"
```

, where `:` is simply a NOP shell builtin.

**Comment by RomanSaveljev** [comment]
I could be working on the issue for the time being. I envision it is an easy fix, but some tests will have to be updated.

**Comment by fsquillace** [comment]
Closing issue.
