### ISSUE TITLE
Force umask to 022 at the beginning of build_image_env

### ISSUE THREAD

**Issue by RomanSaveljev** [fsquillace/junest#114]
The image building script assumes that directories created by root user are readable by others. This is not true in my system, where I have umask `027`. The image builder runs some commands under `sudo` and then tries to jump inside as a real user. This fails with permission denied error.

I think the easiest way to fix is to force umask to 022 at the beginning of the `build_image_env` function.

**Comment by fsquillace** [comment]
Change pushed. Closing issue.
