### ISSUE TITLE
junest hangs trying to exit interactive shell right after `pacman-key --populate`

### ISSUE THREAD

**Issue by RomanSaveljev** [fsquillace/junest#116]
Please see recorded terminal session at https://asciinema.org/a/8yj1fmo9tu0fr3xrb7cn7o4nf

It happens only first time after unpacking the image

**Comment by RomanSaveljev** [comment]
It seems the `proot` itself is hanging. This is what I see in the process tree after typing exit in the shell:

```
$ pstree -plaU 19154
bash,19154 -x /tmp/repo/.cross-dev/3rdparty/junest/bin/junest -f bash
  └─proot-x86_64,19163 -S .cross-dev/layers/basement /bin/sh --login -c bash
```

**Comment by RomanSaveljev** [comment]
Same happens, when I do it under ArchLinux host

**Comment by fsquillace** [comment]
This is similar to https://github.com/fsquillace/junest/issues/65

**Comment by 0atman** [comment]
this happens to me with nvim

```junest -f -- nvim```

Occasionally, when I exit nvim, it will hang and not return control to the terminal. ctrl-c/d doesn't work, but ctrl-z does, and from there I can `kill -9` the process.
