### ISSUE TITLE
pacman error: you cannot perform this operation unless you are root.

### ISSUE THREAD

**Issue by eMPee584** [fsquillace/junest#125]
So, I have checked out junest from git, exported the $PATH and ran junest. The image is downloaded from dropbox and unpacked into .junest, which is now 317MiB in size. However, there's a problem:
```
s0893948@login1:/home/h2/s0893948> junest
proot warning: can't chdir("/home/h2/s0893948/./.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot warning: can't chdir("/home/h2/s0893948/./.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
[I have no name!@login1 /]$ pacman -Syy
error: you cannot perform this operation unless you are root.
[I have no name!@login1 /]$ su
sh: su: command not found
```
Note also the uncommon home path construct:
```
s0893948@login1:/home/h2/s0893948> ls -lahd /home/h2/s0893948 /home/s0893948
drwx------ 12 s0893948 idmuser 4.0K Nov 10 11:00 /home/h2/s0893948
lrwxrwxrwx  1 root     root      11 Nov  4 22:18 /home/s0893948 -> h2/s0893948
```
...what gives..?

**Comment by eMPee584** [comment]
Ok RTFM fail, sorry.
> As fakeroot - Allow to install/remove packages: `junest -f`

The warning about being unable to chdir of course goes away with a simple
```
ln -svi /home/s0893948 /home/h2/
```

**Comment by fsquillace** [comment]
Good to know it was a simple issue ;)

Feel free to star JuNest in github if you like it. It will help the project ;)

Regards,
Filippo
