### ISSUE TITLE
How do I mount bind some directories (manually) to junest environment without editing junest?

### ISSUE THREAD

**Issue by adamcavendish** [fsquillace/junest#130]
How do I mount bind some directories (manually) to junest environment without editing junest?

I have a `/data` directory where I mostly install some softwares and save data samples. If I switch to junest, it just auto bind my home directory to where home locates.

How can I mount bind some extra directories (via config files or manually are both ok)?

**Comment by fsquillace** [comment]
Hi,

Maybe this is what you are looking for: https://github.com/fsquillace/junest#bind-directories

For instance if you what to get your `/data` directory visible in JuNest:

    junest -p "-b /data"

**Comment by adamcavendish** [comment]
Thx. It helps a lot. Probably you should add a message for the help.

**Comment by AwesomeLemon** [comment]
For someone like me who comes here from Google: if you you use namespaces, the proper command is 
``junest ns -b "--bind /data /data"``

**Comment by abhinav010101** [comment]
hi, this bind exists just while the program is executing. how to make this bind permenant?
