### ISSUE TITLE
Is JuNest possible to open x window application ?

### ISSUE THREAD

**Issue by likueimo** [fsquillace/junest#134]
As title
I try to install like as google-chrome-unstable with yaourt
But can not open it
So I guess can not open x window right ?
Sorry I am new in Linux
Maybe this is a stupid question.
Thank a lot !

**Comment by fsquillace** [comment]
As far as i can see there is no package `google-chrome-unstable` existing in AUR.

Anyway, in JuNest it is possible to have graphical applications running. I tried to install `google-chrome` package instead but the problem is that the package contain a suid executable that needs to have root ownership to make it working (see also: https://github.com/fsquillace/junest#suid-permissions):

```
$ junest -f -- yaourt -S google-chrome
...
...
$ junest
[feel@myarch junest]$ google-chrome-stable 
[612:612:1226/174004:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/google/chrome/chrome-sandbox is owned by root and has mode 4755.
Aborted (core dumped)
```

**Comment by likueimo** [comment]
HI, sorry what I installed with yaourt is  `google-chrome-dev`
Thank you for replying me !
When I use junest -f to install  `google-chrome-dev` is also abort 
even execute junest -f to become root user
so could you give a easy example to open a x windows application ?
Thank you very much !

**Comment by fsquillace** [comment]
Could you provide the output you get? So I can understand the error.

You can try to install gvim for instance.

    junest -f -- pacman -S gvim

**Comment by likueimo** [comment]
Thank you ! 
I open gvim, gedit and success !
But `google-chrome` still failed
When I type `junest -f` become root user and 
type `google-chrome-stable`
It only said `Aborted`
Nothing more
So I also tried install firefox with pacman
Open firefox success !
However, firefox also have my host computer firefox bookmarks
So I guess the `google-chrome-stable` command 
access my `~/.config/google-chrome/` folder failed (the folder is 3.9G)
or too more thing interact my host chrome to abort

So I tried to install chromium because of my host do not install chromium
I typed `junest -f` and type `yaourt -S chromium`
after finished install and type `chromium`
```
[root@PHY ~]# chromium 
[11729:11729:1227/033546:FATAL:namespace_sandbox.cc(140)] Check failed: clone_flags & CLONE_NEWUSER. 
Aborted
```
My host system is LinuxMint 17.1
Thank you so nice to teach me ! 
And I guess chromium or chrome is too big like monster to debug it

**Comment by fsquillace** [comment]
Sure no problem.

Chrom* packages looks tricky and I think is because of the SUID.
There is a possibility to make suid executable working on JuNest (https://github.com/fsquillace/junest/issues/59). Still it is not fully tested/integrated in JuNest though.

Regards,
Filippo
