### ISSUE TITLE
Bad handling of background process

### ISSUE THREAD

**Issue by ishitatsuyuki** [fsquillace/junest#135]
It should be possible to fork() in to background and don't be stuck if the user did something background in junest.

**Comment by ishitatsuyuki** [comment]
One more: if proot is running as daemon, it should reuse the session

**Comment by fsquillace** [comment]
Can you provide the output of the commands you executed? AFAIK proot cannot be run as a daemon.

**Comment by fsquillace** [comment]
No response. Closing issue.
