### ISSUE TITLE
pacman 5 update complicates quick start with the default image

### ISSUE THREAD

**Issue by Optiligence** [fsquillace/junest#137]
The current image has an old version of package-query. 
Because no repo is set up for it, a system upgrade breaks due to dependency issues with the pacman update. 
Using [archlinuxfr] would circumvent such issues. 
If that’s unwanted, an image with an up-to-date `package-query` would be nice.

**Comment by fsquillace** [comment]
Hi,

Thanks for checking this. Apparently, the building process did not work because of this update. Now, I have built the new JuNest image for x86_64 and in few minutes I should update the x86 too.

The remaining one will be ARM which I hope I will build the next days.

Thanks again,
Filippo

**Comment by fsquillace** [comment]
ARM image updated too.
Resolving.
