### ISSUE TITLE
Change the default shell

### ISSUE THREAD

**Issue by qiuwei** [fsquillace/junest#142]
How can I change the default shell?

chsh for root doesn't work properly.
I still got the default shell afterwards.

I can't run chsh for the normal user if there is any.

btw: Is there a password for the non-root user? 

Thanks in advance. This is really an excellent work.

**Comment by fsquillace** [comment]
Hey,

To use `chsh` you need to be root. Your os will not allow you to change the system property without being root. To overcome this obstacle you can set the default shell even outside JuNest, and the effect will be visible whenever you enter in JuNest environment.

Another simpler approach is just:

    junest -- <myshell>

For instance for accessing in JuNest using fish shell:

    junest -- /usr/bin/fish

Of course, you need first to install fish inside JuNest.

**Comment by qiuwei** [comment]
Thanks a lot for the instant response!

`junest -- /usr/bin/fish` does the trick.

I am just curious about what you meant by

>  To overcome this obstacle you can set the default shell even outside JuNest, and the effect will be visible whenever you enter in JuNest environment.

Does it mean that junest takes the environment variable $SHELL as the default shell?

**Comment by fsquillace** [comment]
JuNest relies to sh for understanding which shell to run:

    ls -l /bin/sh
    lrwxrwxrwx 1 root root 4 Nov 23 20:20 /bin/sh -> bash

Changing the symlink should do the trick although I would suggest to avoid changing it.

**Comment by ekg** [comment]
Changing this link is not safe. Is there any other way to change the default shell in junest?

**Comment by ekg** [comment]
Nevermind, I've worked around this by setting up a script like this

```bash
#!/bin/bash

exec .local/share/junest/bin/junest -- zsh
```

I then call this as the default shell in tmux and I'm happy!

**Comment by TheHardew** [comment]
I had some problems with `junest -- fish`, namely when hitting ^C `fish` would get somehow intertwined with just `sh`, no commands would work, but as per https://stackoverflow.com/a/39622593 I managed to solve it with setting ENV before launching junest. Junest uses Arch Linux so I think it should work everywhere.
