### ISSUE TITLE
Cloning into a different path than `~/junest` gives an odd error when calling `junest` first

### ISSUE THREAD

**Issue by jchnkl** [fsquillace/junest#146]
```
# ~/.junest/bin/junest -f
ln: failed to create symbolic link '/home/jrk/.junest/etc/mtab': No such file or directory
junest/bin/../lib/core.sh: line 112: /home/jrk/.junest/lib64/ld-linux-x86-64.so.2: No such file or directory
```

Maybe that should be documented or the path should be checked in the installation script?

**Comment by fsquillace** [comment]
I think the problem is that you cloned the code in ~/.junest. That is the location in which the script will download the JuNest image by default.

If you want to change the JuNest image location, change the JUNEST_HOME environment variable.

**Comment by jotrk** [comment]
I see, that makes sense! The `JUNEST_HOME` env variable is also in the documentation.
The only thing that could be done would be to check if ${JUNEST_HOME} exists and refuse operation, just like git does.
