### ISSUE TITLE
curl problem when running junest

### ISSUE THREAD

**Issue by maplewizard** [fsquillace/junest#147]
I run junnest, but it shows:
$./junest
Downloading JuNest...
--2016-05-18 14:49:55--  https://dl.dropboxusercontent.com/u/42449030/junest/junest-x86_64.tar.gz
Resolving dl.dropboxusercontent.com... 37.61.54.158, 200:2:3b18:3ad::
Connecting to dl.dropboxusercontent.com|37.61.54.158|:443... failed: Connection timed out.
Connecting to dl.dropboxusercontent.com|200:2:3b18:3ad::|:443... failed: Address family not supported by protocol.
curl: option -J: is unknown
curl: try 'curl --help' for more information
Error occurred when installing JuNest

**Comment by fsquillace** [comment]
Hi,

That sounds a bit odd. which version of curl do you use?

**Comment by maplewizard** [comment]
curl --version
curl 7.49.0 (x86_64-pc-linux-gnu) libcurl/7.49.0 OpenSSL/0.9.8b zlib/1.2.8 libidn/0.6.5
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: IDN Largefile NTLM NTLM_WB SSL libz UnixSockets

**Comment by fsquillace** [comment]
That's weird. My curl version is: 7.35.0 at it works.

Can you check if `-J` exists? In my case it does:

```
>> curl -h | grep "\-J"
 -J, --remote-header-name Use the header-provided filename (H)
```

**Comment by maplewizard** [comment]
Yes, it exist.
```
 ~ curl -h | grep "\-J"
 -J, --remote-header-name  Use the header-provided filename (H)
```

**Comment by fsquillace** [comment]
TBH, I do not understand why you get this error:

```
curl: option -J: is unknown
curl: try 'curl --help' for more information
```

I feel JuNest is taking another existing `curl` executable in your system.

**Comment by fsquillace** [comment]
Closing this issue as it seems to me a wrong dependency for JuNest. If you have further concerns about this, please reopen it.
