### ISSUE TITLE
Cannot run junest: conditional binary operator expected 

### ISSUE THREAD

**Issue by HumpyBlumpy** [fsquillace/junest#154]
Hi, Im trying to run junest but I get the following error:
utils.sh: line 150: conditional binary operator expected 
utils.sh: line 150: syntax error near `=~'
utils.sh: line 150: `[[ "$answers" =~ "$default_answer"]] || {error "The default answer: $default_answer is wrong."; return $WRONG_ANSWER;}'
core.sh: line 56: conditional binary operator expected

**Comment by fsquillace** [comment]
It looks like there is no space between "$default_answer" and ]]
Which version of junest are you using? Can you update to the last version?

**Comment by HumpyBlumpy** [comment]
Hi, I believe I have the latest version as tried both Method 1 and 2 as you describe in the installation section, both with the same outcome. I copied the error by hand which is maybe why there is no space.

**Comment by fsquillace** [comment]
There was a recent code change but it is weird since the last deployment has completed successfully: https://travis-ci.org/fsquillace/junest

Could you repeat the procedure again on a clean environment?

**Comment by fsquillace** [comment]
Hey, any news?

**Comment by HumpyBlumpy** [comment]
Hi,
I just tried again and got same results.
I checked and I have GNU bash, version 2.05b, which I assume is the problem. Is there anything I can do?

**Comment by fsquillace** [comment]
As explaned here: https://github.com/fsquillace/junest/blob/master/README.md#dependencies

At the moment JuNest cannot be compatible with bash version lower than 4.0 as it requires to do significant changes in the junest script.

Can you update the bash version y any chance?

**Comment by HumpyBlumpy** [comment]
Thanks! I managed to install junest now, after installing latest version of bash in my home directory and changing the first line of the junest files. 

I have another question if you dont mind. I am getting the following error when I try to run TexStudio (which installed fine):
QGtkStyle could not resolve GTK. Make sure you have installed the proper libraries. 

It does open but all the menus are blank. Installing gnu-free-fonts per the instructions helped but it is still not usable. Do you know what am I still missing?
Thanks!

**Comment by fsquillace** [comment]
Maybe you need to install gtk:

```
junest -f -- pacman --noconfirm -Sy gtk2
```

**Comment by HumpyBlumpy** [comment]
That works. Thank you very much!
