### ISSUE TITLE
syntax error in conditional expression: unexpected token `('

### ISSUE THREAD

**Issue by dhiraj113** [fsquillace/junest#155]
I get the following error while running junest executable

junest-master/lib/core.sh: line 56: syntax error in conditional expression: unexpected token `('

Is there a bug in the scripts or is there something wrong with my environment?

**Comment by fsquillace** [comment]
How did you run JuNest? Are you using the last update?

Did you run `git pull` in order to take the last update?

**Comment by fsquillace** [comment]
Hey, any news?

**Comment by dhiraj113** [comment]
Hey, 

I was using the latest version itself. I believe it was due some network issue on my office computer. It worked fine on my home computer. So, I don't think there is anything wrong with the scripts.

Thanks
