### ISSUE TITLE
Executing host programs from a junest session

### ISSUE THREAD

**Issue by mardukbp** [fsquillace/junest#158]
Sometimes I would like to launch programs installed in the host OS from within a junest session. According to the proot manual this should be possible:

> PRoot allows one to mix transparently the emulated execution of guest
> programs and the native execution of host programs in the same
> file-system namespace.  
> 
> This mixed-execution feature is enabled by default when using QEMU
> user-mode, and the content of the host rootfs is made accessible
> through `/host-rootfs`.

I have tried running

`junest -p "-q /opt/qemu/qemu-x86_64-static-x86"`

but I get an error.

How can I achieve this with junest?

**Comment by fsquillace** [comment]
Hi,

Depending on which JuNest architecture you are using it is possible that JuNest is using already the `-q` option. If you specify the `-q` again via `-p`, it will result as having `-q` twice, and that's might be the reason you get an error.

At the moment I am afraid it might be worth using the proot command directly located to: `~/.junest/opt/proot/proot-x86_64`

Closing this. If you have further issue on this, please reopen it.
