### ISSUE TITLE
using the ninja build system with its default parallel mode now crashes

### ISSUE THREAD

**Issue by Optiligence** [fsquillace/junest#160]
I compile stuff inside junest and using `ninja` to build anything fails, but when run with the `-j1` switch, it works. 
Using `make` with more than one job doesn’t fail but is really slow (doesn’t fully utilize the cpu), which was also the case for `ninja` when it still worked. 

Any ideas what the reason for the slowness and crashes could be and if there’s a way to fix it?

**Comment by fsquillace** [comment]
This may due to the limitations of proot. Please switch to the new default backend which is Linux namespace `ns`. It should work in that case. Closing for now.
