### ISSUE TITLE
using your shell's command_not_found handling to use junest-installed commands as though they are native

### ISSUE THREAD

**Issue by 0atman** [fsquillace/junest#162]
**THE WORLD MUST HEAR OF THIS**

Drop this in your shell's config (this is written for zsh, but bash has a similar function):
```shell
function command_not_found_handler(){
    junest -f -- $@ || /usr/lib/command-not-found $1
}
```

And now any commands that are not found on your native linux system, get tried inside of junest, before falling back to the command-not-found command (this is available on ubuntu, your distro may have its own, or you can just echo an error)

I LOVE THIS PROJECT!

**Comment by 0atman** [comment]
I wasn't sure where to put this, and I had to tell someone!

**Comment by 0atman** [comment]
I wasn't sure where to put this, and I had to tell someone!

**Comment by fsquillace** [comment]
Thanks @0atman for this!

I think this idea is really a good candidate for a wiki page that explains how to do such things ;)

Here:
https://github.com/fsquillace/junest/wiki

Potential title:
***Automatic fallback to Junest for not found commands in the native Linux system***

We may want to find out a proper way to do the same thing for bash too. Also, I think `command-not-found` is too tight to Ubuntu distro. I would go more towards a simple `echo` command.

WDYT?

**Comment by 0atman** [comment]
Created! If someone could edit the page and add a bash example, that'd be sweet https://github.com/fsquillace/junest/wiki/Automatic-fallback-to-Junest-for-not-found-commands-in-the-native-Linux-system

**Comment by fsquillace** [comment]
Hey @0atman,

Just to let you know that now there is a new feature which allows to run executables inside junest as they were native:

https://github.com/fsquillace/junest#run-commands-installed-in-junest-directly-from-host

**Comment by 0atman** [comment]
oh amazing! I'll re-install and give it a go :-D
