### ISSUE TITLE
State system requirements or "recommended" kernel version more clearly

### ISSUE THREAD

**Issue by cfriesicke** [fsquillace/junest#172]
I have recently started using junest on a host machine with kernel 2.6.18. So far, it is a nice way to get access to fresh Arch Linux packages while staying entirely within my user privileges. So: thank you very much for releasing junest! It really makes my life easier.

In the manual or README, it is stated that junest works with a recommended kernel version of 2.6.0+ (whatever that means...). However, being on a host machine with kernel 2.6.18, I have encountered some troubles.

It starts with the shipped executables for PRoot and other tools. Running the `file` command on the shipped `proot` binary shows that it is compiled for kernel 2.6.32. This is not necessarily a problem in practice but I routinely have to run `junest -p "-k 2.6.32"` so that PRoot shuts up about the kernel being too old. 

This could be mentioned in the README, i.e. that *any* kernel older than 2.6.32 will generate this warning. My guess is that it can be avoided if all shipped binaries are compiled for lower kernel versions.

The real troubles start when using some of the Arch Linux packages. Some of the software relies on kernel features that PRoot cannot emulate. For example, private futexes were introduced in kernel 2.6.22. A lot of software in the Arch repositories seems to rely on this feature. X11 applications for example, almost always result in PRoot giving the warning: 

    "kompat: this kernel doesn't support private futexes and PRoot can't emulate them.  Expect some troubles...

There is a high correlation with this warning and applications that are crashing. Apart from that, I cannot import python packages that I installed via the `setup.py` mechanism. When I try to import them, python says:

    "The futex facility returned an unexpected error code.Aborted"

(Python packages installed via pacman, however, do not have this problem.)

This tells me that:
- "2.6.0+" should not be recommended as only a subset of Arch packages work without problems
- 2.6.22 is likely the minimum for smooth operation with most applications
- 2.6.32 would be the minimum to be fully compatible with the shipped binaries

We should not discourage users to try junest on older kernels. For example, vim 8.0 and git work flawlessly in my case. However, the information in the README is kind of misleading.

Let me know what you think.

Cheers 
Christian

**Comment by fsquillace** [comment]
Hey @cfriesicke 

Sorry for the delay on this. I did not have time to spend to JuNest lately. 

Thanks for such analysis about the minimum Linux kernel version compatible for JuNest. My tests about this were quite blurry as I relied on an old red hat system (2.6.18 if I recall correctly) in which I installed only few basic program such as vim, then I supposed that all 2.6.0+ should work fine. 

I trust on your tests and I really think they should be included in the README file. Please, could you create a PR for this?

Thanks again,
Filippo
