### ISSUE TITLE
move tmp directory

### ISSUE THREAD

**Issue by ka223** [fsquillace/junest#180]
Hello,

how can I change the tmp directory in junest?

My /tmp is mounted as no exec, I need to move it to another location.

**Comment by fsquillace** [comment]
Unfortunately, JuNest is based on proot and it requires to store a file in /tmp directory.

It is not configurable at the moment.

**Comment by ka223** [comment]
@fsquillace 
Thanks, but implementing would be possible ? 
Maybe something for a feature request ?

**Comment by fsquillace** [comment]
The lastest proot version contains this possibility (although not well documented) via an environment variable.

Until this one https://github.com/fsquillace/junest/issues/161
does not get fixed we cannot update JuNest to the latest proot version.

You might download the proot code a build and use it directly to the junest image although is a bit challenging.

**Comment by fsquillace** [comment]
The recommended alternative for JuNest is using the Linux namespace. Closing for now.
