### ISSUE TITLE
"tig" package requires "libreadline.so.7"

### ISSUE THREAD

**Issue by fabio-porcedda** [fsquillace/junest#181]
After installing the tig package with:
  pacman -S tig

tig
tig: error while loading shared libraries: libreadline.so.7: cannot open shared object file: No such file or directory

I've tried to instal the "readline" package but now nothing works:
pacman -S readline
resolving dependencies...
looking for conflicting packages...

Packages (1) readline-7.0.003-1

Total Download Size:   0.29 MiB
Total Installed Size:  0.72 MiB
Net Upgrade Size:      0.04 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 readline-7.0.003-1-x86_64                             294.7 KiB   314K/s 00:01 [#############################################] 100%
(1/1) checking keys in keyring                                                  [#############################################] 100%
(1/1) checking package integrity                                                [#############################################] 100%
(1/1) loading package files                                                     [#############################################] 100%
(1/1) checking for file conflicts                                               [#############################################] 100%
(1/1) checking available disk space                                             [#############################################] 100%
:: Processing package changes...
(1/1) upgrading readline                                                        [#############################################] 100%
:: Running post-transaction hooks...
(1/1) Updating the info directory file...
/bin/sh: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory
error: command failed to execute correctly

junest
/bin/sh: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory
/bin/sh: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory
Error: Check if the junest arguments are correct and if the kernel is too old use the option junest -p "-k 3.10"

junest -p "-k 3.10"
/bin/sh: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory
/bin/sh: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory
Error: Check if the junest arguments are correct and if the kernel is too old use the option junest -p "-k 3.10"

**Comment by fsquillace** [comment]
The problem is due to the fact that the bash is old and requires `libreadline.so.6` to work, whereas `tig` needs `libreadline.so.7`.

Create a new JuNest environment and install both `readline` and `bash`:

    pacman -S readline bash

**Comment by fabio-porcedda** [comment]
Thanks a lot, your soultion fixes the problem.

Best regards
Fabio

**Comment by fsquillace** [comment]
No problem. This would not have happened if I have had built the latest JuNest image.
Apologies for that.

I am going to build the new image in the next days or so.
