### ISSUE TITLE
No able to change file ownership via namespace mode

### ISSUE THREAD

**Issue by fsquillace** [fsquillace/junest#189]
```
touch /test-file
chown 1000 /test-file
chown: changing ownership of '/test-file': Invalid argument
```

**Comment by madobet** [comment]
> ```
> touch /test-file
> chown 1000 /test-file
> chown: changing ownership of '/test-file': Invalid argument
> ```

You are `root` user at namespace mode, so use 'chown 0 /test-file' instead.

**Comment by fsquillace** [comment]
This has been solved in the latest releases of JuNest.
