### ISSUE TITLE
Running junest gives a copy file error

### ISSUE THREAD

**Issue by yrrah2** [fsquillace/junest#195]
```
$ junest -f
cp: '/etc/host.conf' and '/home/.../.junest//etc/host.conf' are the same file
/home/.../.junest/usr/bin/cp: '/etc/host.conf' and '/home/.../.junest//etc/host.conf' are the same file
```

the ... represents my account name

**Comment by fsquillace** [comment]
Hi @yrrah2 ,

That's strange indeed. The script attempts to use `cp` from your system and if that fails it falls back to the `cp` command from JuNest image.

Is `host.conf` a symbolic link? What are its permissions?

**Comment by sea-grass** [comment]
@yrrah2 Are you running junest from within junest? This happened to me, as when I first ran the command It didn't seem to do anything.

I kept deleting the `/home/.../.junest//etc/...` files until it gave me no errors except for: `Error: Nested JuNest environments are not allowed`, which gave it away.

Checking for the `$JUNEST_ENV` variable shows if you are within JuNest or not.

**Comment by fsquillace** [comment]
My bad. This must be an bug that came from a refactor I did few months ago. I hope to find the time to fix this during the next weeks.

FYI: JuNest is not designed for nested environments.
