### ISSUE TITLE
Current version of firefox is buggy

### ISSUE THREAD

**Issue by DroidFreak32** [fsquillace/junest#198]
Tested in PROOT Mode only
In the latest version of firefox in arch repos, the browser will not connect to any website (though search gives results weirdly enough)

A workaround is to use [firefox-esr](https://aur.archlinux.org/packages/firefox-esr/) from AUR.

If this can be confirmed by others, maybe the workaround can be added in the FAQ section
Also, Chrome/opera doesnt work in proot mode but thats not a big deal, we have firefox.
PS: This project is just brilliant.

**Comment by fsquillace** [comment]
Hey @DroidFreak32 

Is the `~/.junest/etc/resolv.conf` file being copied successfully? Does the file contain the nameservers entries?

**Comment by DroidFreak32** [comment]
@fsquillace Yep I do see 6 nameserver entries

**Comment by DroidFreak32** [comment]
I recently tested firefox quantum. Same issue in it too. Right now firefox-esr is the only browser that works in proot mode. Chrome/opera wont work at all : 

        Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
        [1109/095356.234710:FATAL:zygote_host_impl_linux.cc(182)] Check failed: ReceiveFixedMessage(fds[0], kZygoteBootMessage, sizeof(kZygoteBootMessage), &boot_pid).

**Comment by fsquillace** [comment]
Try with Linux namespaces. `ns` mode. proot is available as secondary backend but not supported as `ns`.
