### ISSUE TITLE
Cannot use yaourt or makepkg or sudo

### ISSUE THREAD

**Issue by yrrah2** [fsquillace/junest#201]
yaourt message:

```

( Unsupported package: Potentially dangerous ! )
==> Edit PKGBUILD ? [Y/n] ("A" to abort)
==> ------------------------------------
==> 

==> ERROR: Running makepkg as root is not allowed as it can cause permanent,
catastrophic damage to your system.
==> ERROR: An unknown error has occurred. Exiting...
Unable to read PKGBUILD
```

makepkg message:

```
==> ERROR: Running makepkg as root is not allowed as it can cause permanent,
catastrophic damage to your system.

==> ERROR: An unknown error has occurred. Exiting...
```

sudo message:

```
sudo: PERM_SUDOERS: setresuid(-1, 1, -1): Invalid argument
sudo: no valid sudoers sources found, quitting
sudo: unable to initialize policy plugin
```

I have gone through the readme a few times and it didn't fix these issues (but it fixed a lot of others)

thank you

**Comment by yinflying** [comment]
yaourt cant run with root  unless you modify some source code in makepkg.  you should search it in  all old issue before you open an new issue  ...

**Comment by yinflying** [comment]
besides , junest cant change to catch the root privilege  with sudo or su  .....

**Comment by yrrah2** [comment]
How can you run something without root inside junest

The system that junest is in doesn't have makepkg and I dont have root to install it so where do I run it from

**Comment by yrrah2** [comment]
I made the edit to makepkg as well

**Comment by yinflying** [comment]
#145  make the makepkg can run with junest root ，this is the only way to run yaourt if you do not have the root privilege of host system...

**Comment by yinflying** [comment]
besides  junest do not support switch user between root and normal ....

**Comment by fsquillace** [comment]
Hi all,

There is no need to change `makepkg` that is done already for you.
As stated in the [description](https://github.com/fsquillace/junest#description) section there is a `yaourt` wrapper called `yogurt`. For the actual `makepkg` (which uses `su`/`sudo`) cannot be used at the moment.

Closing this issue in favor of an old one: https://github.com/fsquillace/junest/issues/59
If you have further issues, please reopen it.

**Comment by yrrah2** [comment]
```
yogurt -S muCommander
su: cannot set groups: Operation not permitted
su: cannot set groups: Operation not permitted
su: cannot set groups: Operation not permitted
```
I still get the same problem with yogurt

**Comment by yrrah2** [comment]
In fact I cannot seem to install anything using yogurt
