### ISSUE TITLE
Ctrl-Z is not working in JuNest

### ISSUE THREAD

**Issue by goduck777** [fsquillace/junest#214]
After starting JuNest and run a command, pressing ctrl-Z does nothing. The suspend function is not working.

Other keys like ctrl-c and ctrl-\ are working. But suspend is very useful.

**Comment by DiagonalArg** [comment]
Do you have a aproblem with your locale settings?  By repairing that using [this work around](https://github.com/fsquillace/junest/issues/214), it solved the ^z problem for me.

**Comment by fsquillace** [comment]
I tried with both `proot` and `ns` and it works. Closing for now.
