### ISSUE TITLE
mpirun complains when installing aur package as root

### ISSUE THREAD

**Issue by aslakstubsgaard** [fsquillace/junest#215]
trying to install scotch from the aur, using yogurt. but when logged in as root, yogurt complains about 'mpirun has detected an attempt to run as root'. while when logged in as a normal user, yogurt wants the sudo password which i can't find any reference on this rep.

solved this by removing 'check' from the pkgbuild, which made the call to mpirun, but would like a better solution.

**Comment by fsquillace** [comment]
Consider that `yogurt` is no longer supported. There is a modified version of `makepkg` in `/opt/makepkg/bin/makepkg`. Give it a try as it should work.

Closing for now.
