### ISSUE TITLE
Unable to use unshare installed to custom prefix

### ISSUE THREAD

**Issue by JonnyHaystack** [fsquillace/junest#220]
I'm trying to use junest without any root privileges. The machine I'm on has an old version of unshare which doesn't support the --user option. I've built the latest version of util-linux from source and installed it to ~/.local/, but junest doesn't seem to respect the ordering in my PATH so I'm not sure how to get it to use the unshare binary which I built.

**Comment by fsquillace** [comment]
Hey @JonnyHaystack 

I think it has to do with this line: https://github.com/fsquillace/junest/blob/master/lib/core/common.sh#L29

We should proably change the order and prioritize PATH over the system directories.

**Comment by JonnyHaystack** [comment]
Yes, agreed 🙂

**Comment by fsquillace** [comment]
Done.
