### ISSUE TITLE
Odd error message when command is not installed.

### ISSUE THREAD

**Issue by DiagonalArg** [fsquillace/junest#224]
When I misprint a command (eg printent rather than printtenv) or a command doesn't exist (eg man), I get an odd error:

```
$ printent LANG
Error: Nested JuNest environments are not allowed

$ man bash
Error: Nested JuNest environments are not allowed
```

**Comment by fsquillace** [comment]
Which host OS are you using?

That error occur when you try to run `junest` within a `junest` session.

**Comment by DiagonalArg** [comment]
I figured it out.  The problem is the `function command_not_found_handle()`.  when the command is misprinted, this function is run, which invokes junest again.
