### ISSUE TITLE
CentOS-7 presenting problem with /usr/lib/ld-linux-x86-64.so.2

### ISSUE THREAD

**Issue by DiagonalArg** [fsquillace/junest#228]
New problem since the server was upgraded to centos-7:

```
$ junest -f
/home/User/.junest/opt/junest/lib/core/common.sh: /home/User/.junest/bin/getent: /usr/lib/ld-linux-x86-64.so.2: bad ELF interpreter: No such file or directory
/home/User/.junest/opt/junest/lib/core/common.sh: /home/User/.junest/bin/getent: /usr/lib/ld-linux-x86-64.so.2: bad ELF interpreter: No such file or directory
/home/User/.junest/opt/junest/lib/core/common.sh: /home/User/.junest/bin/getent: /usr/lib/ld-linux-x86-64.so.2: bad ELF interpreter: No such file or directory
$ pacman -Syu
error: you cannot perform this operation unless you are root.
```

The file ` /usr/lib/ld-linux-x86-64.so.2` which did exist in what I believe was CentOS-6, is no longer present in the newly upgraded machine which is CentOS-7.  I additionally have a home machine based on CentOS-7, and that file is also not present there.  Note that I was having getent problems anyway, even when the file was present.

**Comment by fsquillace** [comment]
I tried in CentOS 7 and it works just fine with `proot` backend. Please check if there is something specific with you image. Closing for now.
