### ISSUE TITLE
FATAL: kernel too old on 2.6.32

### ISSUE THREAD

**Issue by delfer** [fsquillace/junest#232]
Hello!
When I trying to chroot, I am getting:
```
# uname -a 
Linux FrozenCadetblue-VM 2.6.32-042stab134.3 #1 SMP Sun Oct 14 12:26:01 MSK 2018 x86_64 GNU/Linux
# chroot /arch/ /bin/bash 
FATAL: kernel too old
```
I suppose the README is out of date. What is minimal kernel version required?

**Comment by fsquillace** [comment]
Hi,

Kernel is very old indeed. I think you should try to access via `proot` mode:

    JUNEST_HOME=/arch junest proot -f -- /bin/bash

**Comment by delfer** [comment]
@fsquillace I think requirements in README should be updated https://github.com/fsquillace/junest/blame/master/README.md#L129
