### ISSUE TITLE
installing aur packages with makepkg and root execution issues

### ISSUE THREAD

**Issue by aslakstubsgaard** [fsquillace/junest#234]
since yogurt has become depricated i'm installing openfoam from the aur with
```bash
git clone https://aur.archlinux.org/openfoam.git
cd openfoam
makepkg -si
```
this results in
```bash
==> Creating package "openfoam"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Adding install file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: openfoam 7-1 (Mon Nov 25 18:13:21 2019)
==> Installing package openfoam with pacman -U...
error: you cannot perform this operation unless you are root.
==> WARNING: Failed to install built package(s).
```
while running `makepkg -si` in fakeroot enviroment yields
```bash
==> ERROR: Running makepkg as root is not allowed as it can cause permanent,
catastrophic damage to your system.
```

my way around that was subsequently running `pacman -U` from fakeroot
```
pacman -U openfoam-7-1-x86_64.pkg.tar.xz
```

if there's a way around this i'd like to know. but think the readme needs more of a procedure, rather then the one line now given.

also, makepkg can't install repo dependencies without fakeroot. so the procedure if i'm not missing something is

 - first in `junest`, run  `git clone ...` and `makepkg -s` to find out what repo dependencies your missing
 - now in `junest -f`, install missing repo dependencies with `pacman -S ...`
 - and then back in `junest` and the package folder, run `makepkg -s` to build the tar files
 - finally back in `junest -f`, navigate back to the same folder, run `pacman -U ...pkg.tar.xz`

**Comment by fsquillace** [comment]
Which `makepkg` have used?

You need to use the one located in: `/opt/makepkg/bin/makepkg`

**Comment by aslakstubsgaard** [comment]
`which makepkg` gives `/usr/bin/makepkg`, but i don't have a `/opt/makepkg` folder. this junest installation was also initially set up over a year ago. 
installing a fresh junest on another system produces the `/opt/makepkg` folder.

recommendations on how to build it on older installations?

**Comment by TitouanT** [comment]
I think is not clear enough in the readme.
