### ISSUE TITLE
dropbear in junest

### ISSUE THREAD

**Issue by rudosoot** [fsquillace/junest#238]
Hello, I was hoping to be able to run dropbear in my junest environment. I'm able to install and run dropbear on the server, and I'm able to perform the initial connection and auth via the client. After that, however, the connection is immediately terminated with "Broken pipe".

Server:
```
> pacman -S dropbear
> dropbear -E -B -F -R -p 2222
[8334] Jan 28 04:40:16 Not backgrounding
[8335] Jan 28 04:40:26 Child connection from [ip]:49254
[8338] Jan 28 04:40:44 Auth succeeded with blank password for 'root' from [ip]:49258
[8338] Jan 28 04:40:44 Exit (root): chown(/dev/pts/3, 0, 5) failed: Invalid argument
[8338] Jan 28 04:40:44 syslogin_perform_logout: logout(pts/3) returned an error: No such file or directory
```

Client:
```
> ssh -vvv root@[ip] -p 2222
debug2: ssh_connect_direct
debug1: Connecting to [ip] port 2222.
debug1: Connection established.
...
debug2: channel 0: request shell confirm 1
debug3: send packet: type 98
debug2: channel_input_open_confirmation: channel 0: callback done
debug2: channel 0: open confirm rwindow 24576 rmax 32759
debug3: send packet: type 1
packet_write_wait: Connection to[ip] port 2222: Broken pipe
```

Any suggestions on how to fix this?

**Comment by fsquillace** [comment]
I have just tried with `junest proot` and seems to work for me.

**Comment by fsquillace** [comment]
More details:

Server:
```
junest proot -- dropbear -E -B -F -R -p 222
```

Client:
```
ssh -p 2222 localhost
```

**Comment by rudosoot** [comment]
Ah, I've just been using the default `ns`, so perhaps `proot` would have helped. Either way, I was able to patch `openssh` so I can run `sshd` under namespaces, which was what I really wanted in the first place. Closing.

**Comment by ayaka14732** [comment]
@x1ppy Could you elaborate a bit on how to patch `openssh` to run `sshd` under namespaces?

**Comment by x1ppy** [comment]
@ayaka14732 Sure, here's the patch I'm using to mod the arch `openssh` `PKGBUILD` (v8.4p1): https://gist.github.com/x1ppy/a91533dde7c02bcfa6dffec85a6b57e6
