### ISSUE TITLE
LibreOffice on RHEL6 hangs

### ISSUE THREAD

**Issue by jschwartzenberg** [fsquillace/junest#241]
LibreOffice opens a window, but doesn't get any further than that.

Other software (Firefox, Chromium) works fine.

Nothing interesting is printed on stdio.

**Comment by fsquillace** [comment]
Many times this due to dynamic library that needs to be installed separately.

I just tried, in my case I also needed to install openjdk. But after installing it I got this error:

```
$ sudo pacman -S jdk-openjdk
$ lowriter
no suitable windowing system found, exiting.
```

When I installed chromium, it added another dependency (maybe dynamic library) which made libreoffice works well:

```
$ sudo pacman -S chromium
$ lowriter   # <---- works!!
```

**Comment by jschwartzenberg** [comment]
I have Chromium and the OpenJDK installed, but here it doesn't work.
