### ISSUE TITLE
`junest -f pacman -S nano` fails with permission denied error on RHEL 8.1

### ISSUE THREAD

**Issue by penyuan** [fsquillace/junest#248]
Hello,

I am testing out Junest on a RHEL 8.1 system, and I was able to use the recommended method to install Junest and `junest setup` and `junest -f pacman -Syy` ran without errors. I started by installing the fairly simple `nano` via the command `junest -f pacman -S nano`. Unfortunately this fails with:

```
...
[many lines similar to below]
...
warning: warning given when extracting /usr/share/nano/tex.nanorc (Can't set user=0/group=0 for /usr/share/nano/tex.nanorc)
warning: warning given when extracting /usr/share/nano/texinfo.nanorc (Can't set user=0/group=0 for /usr/share/nano/texinfo.nanorc)
warning: warning given when extracting /usr/share/nano/xml.nanorc (Can't set user=0/group=0 for /usr/share/nano/xml.nanorc)
could not change the root directory (Operation not permitted)
error: command failed to execute correctly
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
could not change the root directory (Operation not permitted)
error: command failed to execute correctly
```

I can also confirm that running `junest -f pacman -Syu` fails with a ton of `could not change the root directory (Operation not permitted)` and `(Can't set user=0/group=0 for [a certain file/path])` errors.

Looks like permissions problems, but I can't figure out what's wrong. Can anyone please advise? Thanks!

**Comment by fsquillace** [comment]
Thanks. I was able to reproduce the issue. We may need to change the way `-f` works.

Try the normal user and run `sudo` instead:

```
$ junest
sudo pacman -Sy nano
```

**Comment by penyuan** [comment]
> Try the normal user and run `sudo` instead

I tried this with the same errors. I tried `junest pacman -Syu` to install updates, full output [here](https://bin.disroot.org/?e34edba38933efd8#J7Hr4qNdsufVMFJeUDnRDoTVngZWrG1pgavZXcvUXXJx).

Lots of `(Can't set user=0/group=0 for [path to a file])`

**Comment by fsquillace** [comment]
Even though it shows the message it should install the package correctly anyway: 
https://github.com/fsquillace/junest#cant-set-user-and-group-as-root

**Comment by penyuan** [comment]
> Even though it shows the message it should install the package correctly anyway:
> https://github.com/fsquillace/junest#cant-set-user-and-group-as-root

Ah I see. After running `sudo pacman -S nano`, `nano` was indeed installed and looks usable so far. Thank you!

You did say we might need to change the way `-f` works earlier. How can I help with that?

**Comment by fsquillace** [comment]
`junest ns -f` uses an option from the backend bwrap to simulate fakeroot: `--uid 0` [source](https://github.com/fsquillace/junest/blob/master/lib/core/namespace.sh#L109). The normal use can use `sudo` which is based on the combination of `fakechroot fakeroot` [source](https://github.com/fsquillace/junest/blob/master/pkgs/sudo-fake/PKGBUILD#L39). One way would be to make sure they both use the same behavior but it would require to see whether side effects could come from it.

**Comment by penyuan** [comment]
OK, well if it's every implemented I'd be happy to help test it.

**Comment by fsquillace** [comment]
This has been solved now. Resolving.
