### ISSUE TITLE
`junest -u` fails with `Invalid option -u`

### ISSUE THREAD

**Issue by penyuan** [fsquillace/junest#249]
As indicated in my [other issue #248](https://github.com/fsquillace/junest/issues/248), I am trying Junest on a RHEL 8.1 system, which according to [issue #229](https://github.com/fsquillace/junest/issues/229) supports user namespaces.

However, when I run the simple command `junest -u`, I get a one line error saying:

```
Invalid option -u
```

I thought `-u` is the option for using user namespaces? `junest --help` doesn't say anything about how to use user namespaces either. What am I missing? Thank you.

**Comment by fsquillace** [comment]
`-u` does not exist as an option anymore.

Run `junest --help` for more info.

User namespace is the default backend. Just run `junest` or the equivalent `junest ns` to activate this backend.
