### ISSUE TITLE
Proot not working properly

### ISSUE THREAD

**Issue by Zoradius** [fsquillace/junest#255]
Hello everyone,

I've been trying to run JuNest for a bit now (really love the idea), but as I am unprivileged and namespaces are disabled (on Debian GNU/Linux 10) I have to work in proot mode. However once I start up `junest proot`  I get the following message:  
`proot info: pid 852541: terminated with signal 11`  
`Warn: Proot is not properly working. Disabling SECCOMP and expect the application to run slowly in particular when it uses syscalls intensively.`  
As I am not too savy I have since compiled proot seperately and it seems to work fine, but I really want the ease of use of JuNest. Is there a way to specify the proot directory or does anyone have a tip regarding the above error message?

Thanks in advance.

Edit: Spelling

**Comment by fsquillace** [comment]
Hi, that's a fair concern. Have you try to use `--backend-command` to specify your proot binary?

**Comment by ceen23** [comment]
I have the same problem and dont understand @fsquillace answer.
Using Debian hence junest ns doesnt work I need to get Proot to work.

**Comment by fsquillace** [comment]
The current version of `proot` used by junest may not work properly for such system like debian. If you compile proot you will get a new binary which you can use together with junest:

```
junest proot --backend-command /path/to/the/new/compiled/proot
```
Hopefully that makes things working.
