### ISSUE TITLE
Compatibility with MacOS

### ISSUE THREAD

**Issue by csantosb** [fsquillace/junest#259]
Used to the benefits of Arch, I'm a little worried about having to use a Mac laptop at some time soon.

Is junest compatible with mac os ? It would be great to get full arch within mac laptops.

**Comment by fsquillace** [comment]
Currently JuNest cannot support Mac. The only way would be to explore solutions based on QEMU given that linux and OSX systems are very different and a virtualisation layer is required. It is not in the plan to explore this yet.

**Comment by csantosb** [comment]
Thanks for this great package anyway.
