### ISSUE TITLE
A rather large ambiguity in the README

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [fsquillace/junest#276]
'The lightweight Arch Linux based distro that runs upon any Linux distros without root access' is ambiguous between the following two meanings.

1) The lightweight Arch Linux based distro that runs (without root access) upon any Linux distro.
2) The lightweight Arch Linux based distro that runs upon any Linux distro that lacks root access.

I think that you mean 1. So I suggest that you change your sentence to 1.

 is an Arch-based version of Linux 

2)

**Comment by fsquillace** [comment]
Makes sense. I will modify it to: `The lightweight Arch Linux based distro that runs, without root privileges, upon any Linux distro`

**Comment by fsquillace** [comment]
https://github.com/fsquillace/junest/pull/280
