### ISSUE TITLE
Need to republish http://fsquillace.github.io/junest-site

### ISSUE THREAD

**Issue by nmstoker** [fsquillace/junest#277]
The details on http://fsquillace.github.io/junest-site are out of date in comparison to your README in the repo. It looks like you need to republish it.

For example, your site mentions yaourt which has been unmaintained for something like three or four years!

**Comment by fsquillace** [comment]
Thanks for catching this! Yes, I have been lacking to update it constantly. I'd need to find a way to automate the republish into the site every time a new JuNest code change gets merged to `master` branch. 

I updated the site now manually. Resolving.
