### ISSUE TITLE
`junest` fails on immutable filesystems

### ISSUE THREAD

**Issue by dryan7** [fsquillace/junest#284]
There are cases where `junest` result in an error similar to :
 ```
cp: cannot create regular file '/home/ieltan/.junest//etc/netgroup': Permission denied
/home/ieltan/.junest/usr/bin/cp: cannot create regular file '/home/ieltan/.junest//etc/netgroup': Permission denied
```
This file has read-only permissions `-r--r--r-- 1 root root 0  1 janv.  1970 /etc/netgroup` on immutable filesystems, `junest` successfully copies this file on the first run but at the second it tries to copy over it (hence deleting it) but because the permissions carries over it doesn't work `-r--r--r-- 1 ieltan users 0 27 déc.  14:35 .junest/etc/netgroup`. I could to circumvent this either by entering `junest -n` or changing junest behavior to use `cp -f`

**Comment by dryan7** [comment]
Also I am using NixOS for the record

**Comment by fsquillace** [comment]
Thanks for raising this issue @dryan7 ! I placed the fix to `dev` branch.

Closing.
