### ISSUE TITLE
Makepkg unresolved?

### ISSUE THREAD

**Issue by GentlemanOfFate** [fsquillace/junest#296]
The makepkg command refuses to work because it thinks I'm working under root even though JuNest is launched. 
==> ERROR: Running makepkg as root is not allowed as it can cause permanent,
catastrophic damage to your system.

The problem was mentioned previously in the issues, and the latest solution seems to have been an inclusion of edited makepkg file:

"`yogurt` has been deprecated. For now, the way to install package is by using a modified version of `makepkg` in `/opt/makepkg/bin/makepkg` which syntax is the same as the original."
_Originally posted by @fsquillace in https://github.com/fsquillace/junest/issues/59#issuecomment-546095446_

However, my opt folder is empty, so something must've changed about it over the latest 3 years or so. Is there an opportunity to use this makepkg command now?

**Comment by fsquillace** [comment]
Hi,

You should be able to use `makepkg` in `ns` (not in `proot`) mode. Generally, you can install package from AUR via `yay` as explained here: https://github.com/fsquillace/junest#install-packages-from-aur

**Comment by GentlemanOfFate** [comment]
> Hi,
> 
> You should be able to use `makepkg` in `ns` (not in `proot`) mode. Generally, you can install package from AUR via `yay` as explained here: https://github.com/fsquillace/junest#install-packages-from-aur

Thanks for the answer!
Unfortunately, I'm forced to use `proot` because my Linux version is too old, and I've found a workaround only through `junest proot -b "-k ..."`
Or is there also a workaround for `ns`?

**Comment by fsquillace** [comment]
Unfortunately, I am not supporting the usage of Proot with AUR. You may try to use `yay` with proot but afaik it does not work.

**Comment by GentlemanOfFate** [comment]
> Unfortunately, I am not supporting the usage of Proot with AUR. You may try to use `yay` with proot but afaik it does not work.

Can I mask my old kernel version when using `ns`? To use `ns` instead of `proot` and hence make use of `yay`
Right now I know I can work from old Linux only with `proot -b "-k 4.4"`

**Comment by fsquillace** [comment]
AFAIK, you can't do it with `ns`. The only way of using `ns` is to have user namespace enabled but old kernel version either do not have such namespace or they have it disable (enabling the user namespace requires root privileges).

**Comment by GentlemanOfFate** [comment]
> AFAIK, you can't do it with `ns`. The only way of using `ns` is to have user namespace enabled but old kernel version either do not have such namespace or they have it disable (enabling the user namespace requires root privileges).

Okay, and why does JuNest require at least v 4.4 of kernel? When something like v. 2.X or 3.X is written in the readme. If it can't support such old versions now, I think it'd be better to update the description
