### ISSUE TITLE
(Question) How to run apps from host inside junest

### ISSUE THREAD

**Issue by aspizu** [fsquillace/junest#298]
Host operating system: Elementary OS

I want to run vscode from the host inside junest.

**Comment by fsquillace** [comment]
Not sure I follow the issue here. Did you find issue installing the vscode in elementary OS? What's the error? Closing for now until we get a more complete description of the problem.

**Comment by aspizu** [comment]
vscode is installed in elementary OS
i want to run vscode from junest, so when i execute "codium folder" it will open that folder in vscode but im inside a shell running in junest

**Comment by fsquillace** [comment]
> i want to run vscode from junest

If it is installed in elemetary OS, I am not sure you could do that. Have you tried installing vscode in Junest instead?

**Comment by aspizu** [comment]
yes i can install vscode in junest instead
though this still is a issue in some cases
ex:
opening links from junest inside the web browser which is installed on the host
opening folders in the file manager installed on the host
