### ISSUE TITLE
Cloudfront server is down

### ISSUE THREAD

**Issue by Jeko83** [fsquillace/junest#303]
Hi, when downloading the junest image from cloudfront, it just says  "No address associated with hostname". I think the server is down, it might require a reupload.
![Screenshot 2022-11-02 170453](https://user-images.githubusercontent.com/58703702/199540670-ffe9452d-d529-4c37-88fd-a7b89cb828b8.png)
I also tried an older build that pulled the image from amazon AWS, but the link is down as well, permisison denied.

**Comment by fsquillace** [comment]
Hi, please `git pull` the latest junest version.

**Comment by Jeko83** [comment]
I would git pull if I had the possibility. I am connecting via ssh to a remote machine and my user does not have git nor other useful packages, I want to install junest for that specific reason. I have no way to contact administrator. The junest setup script works fine, it's just that the server is unreachable. It worked fine like 1 month ago, so it would be helpful if you could get the image back up on that server, thank you very much!

**Comment by fsquillace** [comment]
If you are able to `ssh` to the machine then you can simply clone the junest git repo locally and `scp` to the remote machine.

**Comment by Jeko83** [comment]
ohhh nice, ty. Super amazing job on the project btw, keep it up
