### ISSUE TITLE
pacstrap: remove obsolete option '-d' completely

### ISSUE THREAD

**Issue by linhua55** [fsquillace/junest#308]
https://github.com/fsquillace/junest/blob/77acbf5214ee84841bf7daedcf3dad5d88ce7798/lib/core/build.sh#L65

refer to https://github.com/archlinux/arch-install-scripts/commit/91562aa99cd8237a2dec1aff5101949e40bf7d75

**Comment by fsquillace** [comment]
Thanks for raising this! Solved in the latest version.
