### ISSUE TITLE
"sudo rm -rf --no-preserve-root /" erases host files, not junest files

### ISSUE THREAD

**Issue by 123ldk** [fsquillace/junest#311]
I don't know if this was me misunderstanding how this was supposed to work vs an actual bug, but I accidentally wiped a good chunk of my files because of this.

I had modified my bashrc with "export PATH="$PATH:~/.junest/usr/bin_wrappers", so maybe that did it in?

**Comment by fsquillace** [comment]
Can you provide more info?

Did you do this within junest? what are the exact sequence of steps?
