### ISSUE TITLE
bind /run/user/<id>

### ISSUE THREAD

**Issue by Nidrop** [fsquillace/junest#313]
Firstly, is there an issue with tmpfs in /run (ns mode)? And why not bind /run/user/$(id -u)?

**Comment by fsquillace** [comment]
Yeah, that sounds a good idea to bind as default. As of now, you can do that using `-b` option.

**Comment by fsquillace** [comment]
Added here: https://github.com/fsquillace/junest/commit/65c45517e15f4e0f3efa8245e8fec20c53c51b3e

Thanks for raising this!
