### ISSUE TITLE
multi-call wrapper

### ISSUE THREAD

**Issue by Nidrop** [fsquillace/junest#318]
I suggest handling wrappers the same way [busybox does](https://www.redbooks.ibm.com/abstracts/tips0092.html). 
All exported binaries would be links to one `junest-wrapper` which does something like:
```
if [ "$0" != "junest-wrapper" ]; then
    # execute $0 in junest
fi
```

**Comment by fsquillace** [comment]
I love the idea. It will make the wrappers cleaner. I will give it a try at some point. Thanks!

**Comment by fsquillace** [comment]
Change merged into `master` branch.
