### ISSUE TITLE
Add junest-export to export applications from Junest to the host quickly

### ISSUE THREAD

**Issue by ivan-hc** [fsquillace/junest#323]
Hi, just done a PR at https://github.com/fsquillace/junest/pull/322

This is not much but an idea to improve the Junest's experience.

This is the content of my simple script to export my apps:

https://github.com/ivan-hc/junest/blob/master/bin/junest-export

For more improvements I need a lot of time I've not due to my real job. However I would be happy too if you check and improve this script too.

You can also test my script as a standalone program:

    wget https://raw.githubusercontent.com/ivan-hc/junest/master/bin/junest-export
    chmod a+x ./junest-export
    ./junest-export

Cheers.

**Comment by fsquillace** [comment]
Thanks @ivan-hc! Various improvements can be taken by directly looking at the equivalent code in distrobox: https://github.com/89luca89/distrobox/blob/main/distrobox-export

Some ideas for anyone willing to look at this work:

- IMO, we should start simple and consider the export app operation only (ignoring any other actions like deletion, service, completion, etc) and a very small set of options (e.g. i would not spend much time on `--media`)
- The command does not have to be precisely the same syntax as distrobox-export
- We can re-use the same executable `junest` and add an additional `export` command
- An example syntax:
  - `junest export --desktopfile <nameofdesktopfile> --sudo`
  - `junest export --desktopfile redshift-gtk --sudo`


Also, adding as reference a related wiki page on how to create such desktop files manually on the host: https://github.com/fsquillace/junest/wiki/How-to-create-desktop-launchers-on-programs-installed-in-JuNest

Regards,
Filippo
