### ISSUE TITLE
ack command isn't added to bin_wrappers

### ISSUE THREAD

**Issue by hodapp512** [fsquillace/junest#324]
I try according to the instructions:

```
export PATH="$PATH:~/.junest/usr/bin_wrappers"
sudoj pacman -S ack
ack
```
I get:
```
The program 'ack' is currently not installed. To run 'ack' please ask your administrator to install the package 'ack-grep'
```

But it doesn't look like the bin_wrapper for the command is ever generated.

**Comment by fsquillace** [comment]
The wrapper mechanism look at the executables located into `/usr/bin` only. `ack` is located into a directory inside the `bin`. One possible solution is to gather all directories in `PATH` when such variable is initiated during a Junest session.

**Comment by fsquillace** [comment]
For bin paths different from `/usr/bin` they can be created manually: https://github.com/fsquillace/junest/pull/326
