### ISSUE TITLE
How to disable warning about config.gz

### ISSUE THREAD

**Issue by akvadrako** [fsquillace/junest#328]
I am using junest on latest Fedora Silverblue and every time I get this warning:

```
Could not understand if user namespace is enabled. No config.gz file found. Proceeding anyway...
```

I understand you want to check if user namespaces are supported, but wouldn't a better method be to check for the existence of `/proc/$$/ns/user` ?

**Comment by fsquillace** [comment]
Thanks for pointing this out. Some older linux kernel versions do not have that `user` file AFAIK. I am going to add this additional check to avoid printing the warning in such scenario.

**Comment by fsquillace** [comment]
Merged to master. Resolving. Thanks!
