### ISSUE TITLE
Can not install packages and display this error: could not find database

### ISSUE THREAD

**Issue by GHGS169** [fsquillace/junest#333]
I am running junest in openSUSE Leap . When I try to install package I get the following error :
```
error: failed to prepare transaction (could not find database)
```
How to solve the problem ?

**Comment by fsquillace** [comment]
What command did you run?

**Comment by GHGS169** [comment]
The junest is just  installed then run command of "junest -f". 
And I have  run "pacman -Syy" first but  useless.

**Comment by fsquillace** [comment]
Can you provide more info? what are the commands you are running? what's the  output? have you tried with proot?
