### ISSUE TITLE
I'm using puppy linux and junest complain about this?

### ISSUE THREAD

**Issue by lucasmz1** [fsquillace/junest#343]
You cannot access with root privileges. Use --groot option instead.
how do pass root passowrd using groot ? 
I've tried groot but doesn't work.
by the way I am using for an appimage when mounted on the system it doesn't work.

**Comment by fsquillace** [comment]
groot mode requires real root permissions. What are the commands you are trying to run? what do you want to achieve? Did you try `proot` or `ns` mode first?
