### ISSUE TITLE
when junest install idea or other , they will open file, how to mount the host os file or folder in junest virtual env

### ISSUE THREAD

**Issue by newyorkthink** [fsquillace/junest#346]

**Comment by fsquillace** [comment]
Please provide more info by following: https://github.com/fsquillace/junest/blob/4d2d0fcb840d9266a39deb0acf2afc44973bf5f3/CONTRIBUTING.md

**Comment by fsquillace** [comment]
This might help: https://github.com/fsquillace/junest?tab=readme-ov-file#bind-directories
