### ISSUE TITLE
[DOC] `pacman` doesn't work without sudo

### ISSUE THREAD

**Issue by NightMachinery** [fsquillace/junest#348]
When I followed the instructions in the readme, `pacman` complained about needing to be run with sudo.

So I defined this alias:
```
alias sudo-junest="${HOME}/.junest/usr/bin_wrappers/sudo"
```
and used `sudo-junest pacman ...`, which worked.

Is this the intended way to use junest? Anyhow, the docs probably need a fix, as they don't work as they are.

**Comment by fsquillace** [comment]
Please follow https://github.com/fsquillace/junest/blob/4d2d0fcb840d9266a39deb0acf2afc44973bf5f3/CONTRIBUTING.md

Can you provide the exact section in readme that does not work? What are the exact steps you run?

**Comment by NightMachinery** [comment]
The exact place that does not work is here:
- https://github.com/fsquillace/junest#install-packages-from-aur
```
pacman -S base-devel
```

This results in the following error:
```
❯ pacman -S base-devel

error: you cannot perform this operation unless you are root.
```

After looking through the other sections of the readme, I think you already have a `sudoj` which is almost the same as my alias `sudo-junest`. So the lines of the readme that use `pacman` should also include `sudoj`.

**Comment by fsquillace** [comment]
Usage of `sudo` is not required and depends on which backend is being used. `-f` mode does not need `sudo` for instance.
