### ISSUE TITLE
junest has outdated yay

### ISSUE THREAD

**Issue by Kreijstal** [fsquillace/junest#360]
You might have to use the yay from git and not the one that comes with junest in case you do pacman -Syu as of today.

**Comment by fsquillace** [comment]
Thanks @Kreijstal for the headsup! I replaced yay with yay-git [here](https://github.com/fsquillace/junest/blob/master/lib/core/build.sh#L79).

The newest JuNest image should have both yay-git and pacman7 by default. I updated the junest package repository too so if you have an existing JuNest environment installed, you can replace yay with yay-git during yay-git installation: `pacman -S yay-git`.
