### ISSUE TITLE
Add a config file with user mounts --bind

### ISSUE THREAD

**Issue by rcoacci** [fsquillace/junest#64]
It would be nice to have a config file (probably inside JUJU_HOME or something) with extra user specified paths to bind, so the command goes from `juju -p -b /myworkdir mycommand` to `juju mycommand` with /myworkdir automagically mounted on the fakechroot (the same way `proot -S` does)

**Comment by fsquillace** [comment]
Hi Rodrigo,

I was thinking on something like that too but, at the end, I ended up by simplify things a bit. For instance, you can still use aliases like this:

    alias jj="juju -p '-b /mnt/filix'"
    jj ls -l /mnt/filix
    total 0

I hope this satisfy your request.

Regards,
Filippo

**Comment by rcoacci** [comment]
I have though about that too, but if you have a lot of dirs you want to mount it becomes very error prone. Anyway, thanks for your reply. If I have the time I'll try to make a patch for that.

**Comment by fsquillace** [comment]
As far as I know there is no such feature in Docker either. I guess the reason could be the fact that it does not add much value and, as a cons, it could happen an existing config file may hide behavior that is unexpected from the user.

**Comment by fsquillace** [comment]
Closing this as an old issue. We are going to reconsider this if someone else is interested.
