### ISSUE TITLE
Odd passwd configuration issue

### ISSUE THREAD

**Issue by philrosenberg** [fsquillace/junest#81]
Hi
I thought I'd let you know about an odd passwd configuration issue I have come accross. After installing juju I logged in and my bash promp was 
[I have no name!@host ~]$
After some searching I found this was because my /etc/passwd file did not have my user name in. My system also has a /etc/passwd- file which I don't appear to be able to view, perhaps it is in there? Because juju links to /etc/passwd it couldn't find my username from my uid.

This was causing me many issues, such as suddenly juju would think files didn't exist, pwd didn't work, ssh couldn't find my ~/.ssh directory. I worked around it by creating a ~/.jujupasswd directory and creating the following script which I run to start juju

cp /etc/passwd $HOME/.jujupasswd/passwd
echo $USER:x:`id -u`:`id -g`:$USER:$HOME:$SHELL >> $HOME/.jujupasswd/passwd
juju -p "-b $HOME/.jujupasswd/passwd:/etc/passwd" "$@"

You may be able to come up with a more elegant solution than this if you feel you need to, but I thought I would post this in case it helps anyone else in a similar situation.

**Comment by fsquillace** [comment]
Hi,

The system should contain the /etc/passwd with the info about your user. Can you tell me which linux distro are you using? Are you sure you have setup the user properly in your system?
If you have privileges you can try to add a new user and see if it populates the /etc/passwd file:

    useradd -m myuser

Similarly on the solution you mentioned, we can:
- Check if the /etc/password is readable and contains the user info
- If so, bind it to JuJu environment
- otherwise generate an ad-hoc file

This looks mostly a rare case which I am not sure it is worth taking into account. Leaving this issue open to see if other people encounter the same problem.

Thanks for spotting this.

**Comment by philrosenberg** [comment]
Hi Filippo

Yes, it should indeed, but for whatever reason it doesn't.

$cat /proc/version gives me

Linux version 2.6.32-504.8.1.el6.x86_64 (
mockbuild@x86-002.build.bos.redhat.com) (gcc version 4.4.7 20120313 (Red
Hat 4.4.7-9) (GCC) ) #1 SMP Fri Dec 19 12:09:25 EST 2014
 This is a server in a high performance facility. I don't have privileges
(which is why I am using juju) so I can't do anything with the passwd file
or useradd command. I tried calling useradd in juju -f, but this added the
user to a different file somewhere I think and didn't seem to help. I'll
leave it up to you if you feel you wish to address this. If not then
perhaps a note in your readme pointing to the workaround might be useful in
case anyone else comes across this.

Phil

**Comment by assaf758** [comment]
The most likely reason that a user name does not appear in /etc/password is that the server is using some name service (like LDAP or Active-Directory) to store user information.

You can verify that by doing cat /etc/nsswitch.conf  (if there is lsass or nis configured on the passwd entry, then the above is probably the case).

I had the same issue for user name as well as group names, so I enhanced Phil's script to take care of groups as well:

#!/bin/bash
JUNEST_CFG="$HOME/.config/junest"
mkdir -p $JUNEST_CFG/
cp /etc/passwd $JUNEST_CFG/passwd
cp /etc/group $JUNEST_CFG/group
echo $USER:x:$(id -u):$(id -g):$USER:$HOME:$SHELL >> $JUNEST_CFG/passwd
for i in $( id -G ); do
         getent group $i | awk -F':' '{print $1 ":" $2 ":" $3 ":"}' >> $JUNEST_CFG/group
done    
junest -p "-b $JUNEST_CFG/passwd:/etc/passwd -b $JUNEST_CFG/group:/etc/group" "$@"

Thx,
Assaf

**Comment by JulianKoenig** [comment]
Had the same issue. When launching JuNest without any parameters (as "normal" user)
```
junest
```
 my prompt would look like this
`[I have no name!@host ~]$ `
While fakeroot (`junest -f`) was working fine.

Like with @philrosenberg your recommendations unfortunately didn't help.

And indeed, as @assaf758 stated my working environment was configured to using LDAP. 
`cat /etc/nsswitch.conf`revealed the following:
```
[...]
passwd: files ldap 
group: files ldap 
[...]
```

So thx @assaf758 and @philrosenberg , your script presumably fixed the issues deriving from this problem.

**Comment by fsquillace** [comment]
@assaf758 any reason why you did not use `getent` for getting  the user info instead of composing it via `echo` command?


`getent passwd <myusername>`

**Comment by fsquillace** [comment]
@assaf758 @philrosenberg @JulianKoenig any suggestion about the https://github.com/fsquillace/junest/commit/4cb62794f1f00b3a062e54caec736fe2622fe9be is welcome.

I will add unit tests afterwards.

**Comment by fsquillace** [comment]
https://github.com/fsquillace/junest/pull/152
